### ISSUE TITLE
Local Region Swapping

### ISSUE THREAD

**Issue by ArlenCHEN** [zhujiapeng/resefa#2]
Dear Authors,

Awesome work! And thanks for publishing the code to the community!

I was wondering if this work supports local region swapping, i.e., replacing a source image's mouth with another reference image's mouth. Similar to [this](https://arxiv.org/pdf/2004.14367.pdf)

**Comment by Cecil-x** [comment]
how can I convert the pkl from stylegan2 to pth?

**Comment by zhujiapeng** [comment]
No. This work aims at finding the local editing directions instead of the specific style in the local region of an image.

**Comment by ArlenCHEN** [comment]
Thanks!
